"use client";

import { FormEvent, useEffect, useState } from "react";

type Client = { id: string; name: string };
type Project = { id: string; projectCode: string; name: string; status: string; client: Client; _count: { tasks: number; milestones: number } };
export function ProjectsPage() {
  const [projects, setProjects] = useState<Project[]>([]); const [clients, setClients] = useState<Client[]>([]); const [error, setError] = useState(""); const [form, setForm] = useState({ name: "", clientId: "", type: "", dealValue: "", expectedDeliveryDate: "" });
  async function request(url: string, options?: RequestInit) { const response = await fetch(url, { ...options, headers: { "Content-Type": "application/json" } }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Request failed"); return data; }
  async function load() { try { const [projectData, clientData] = await Promise.all([request("/api/projects"), request("/api/clients")]); setProjects(projectData.projects); setClients(clientData.clients); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load projects"); } }
  useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); try { await request("/api/projects", { method: "POST", body: JSON.stringify({ ...form, dealValue: form.dealValue ? Number(form.dealValue) : undefined }) }); setForm({ name: "", clientId: "", type: "", dealValue: "", expectedDeliveryDate: "" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create project"); } }
  return <section className="space-y-6"><div><p className="text-sm font-medium text-brand-600">Delivery</p><h1 className="text-3xl font-semibold text-ink">Projects</h1><p className="mt-2 text-slate">Turn won business into visible delivery work.</p></div><div className="grid gap-6 xl:grid-cols-[360px_1fr]"><form onSubmit={submit} className="space-y-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-ink">New project</h2><label className="block text-sm font-medium text-ink">Project name<input className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label className="block text-sm font-medium text-ink">Client<select className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" value={form.clientId} onChange={(e) => setForm({ ...form, clientId: e.target.value })} required><option value="">Select client</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label>{[["type", "Type"], ["dealValue", "Deal value"], ["expectedDeliveryDate", "Expected delivery"]].map(([key, label]) => <label className="block text-sm font-medium text-ink" key={key}>{label}<input className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" type={key === "dealValue" ? "number" : key === "expectedDeliveryDate" ? "date" : "text"} value={form[key as keyof typeof form]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>)}<button className="w-full rounded-lg bg-brand-600 px-4 py-2 font-medium text-white hover:bg-brand-700" type="submit">Create project</button></form><div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold text-ink">Project portfolio</h2>{error && <p className="mt-2 text-sm text-red-600">{error}</p>}</div><div className="divide-y divide-slate-100">{projects.length === 0 ? <p className="p-5 text-sm text-slate">No projects yet.</p> : projects.map((project) => <div className="flex items-center justify-between gap-4 p-5" key={project.id}><div><p className="font-medium text-ink">{project.name}</p><p className="text-sm text-slate">{project.projectCode} · {project.client.name}</p></div><div className="text-right"><span className="rounded-full bg-brand-50 px-2 py-1 text-xs font-semibold text-brand-700">{project.status}</span><p className="mt-1 text-xs text-slate">{project._count.tasks} tasks · {project._count.milestones} milestones</p></div></div>)}</div></div></div></section>;
}
