"use client";
import Link from "next/link";
import { useResource } from "@/components/ui/resource";
import { EmptyState, LoadingSkeleton, Notice, SectionHeader, StatusBadge } from "@/components/ui/primitives";

type Project = { id: string; projectCode: string; name: string; description?: string | null; projectType: string; status: string; priority: string; progress: number | null; family?: { name: string } | null; department?: { name: string } | null; client?: { name: string } | null; owner?: { fullName: string } | null; manager?: { fullName: string } | null; technicalOwner?: { fullName: string } | null; modules: { id: string; name: string; status: string; _count: { tasks: number } }[]; tasks: { id: string; title: string; status: string; priority: string }[]; members: { id: string; projectRole: string; user: { fullName: string; role: { name: string } } }[] };
export function ProjectDetailPage({ id }: { id: string }) {
  const { data, loading, error } = useResource<{ project: Project }>(`/api/projects/${id}`, "project");
  if (loading) return <LoadingSkeleton rows={8} />;
  if (error || !data) return <Notice>{error || "Project could not be loaded."}</Notice>;
  const project = data.project;
  return <section><p className="eyebrow">04 / Delivery / Project</p><div className="page-header"><div><p className="mono text-gradient-orange">{project.projectCode}</p><h1>{project.name}</h1><p>{project.description || "A scoped delivery workspace with visible ownership, modules, tasks, and activity."}</p></div><Link className="button button-secondary" href="/projects">← All projects</Link></div><div className="grid gap-6 md:grid-cols-4"><div className="surface-card"><p className="eyebrow">Type</p><p className="record-title">{project.projectType.replaceAll("_", " ")}</p></div><div className="surface-card"><p className="eyebrow">Status</p><StatusBadge status={project.status} /></div><div className="surface-card"><p className="eyebrow">Progress</p><p className="record-title">{project.progress === null ? "Not calculated" : `${project.progress}%`}</p></div><div className="surface-card"><p className="eyebrow">Family</p><p className="record-title">{project.family?.name ?? "—"}</p></div></div><div className="work-grid mt-8"><div className="records"><SectionHeader title="Modules" meta={`${project.modules.length} defined`} />{project.modules.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Module</th><th>Status</th><th>Tasks</th></tr></thead><tbody>{project.modules.map((module) => <tr key={module.id}><td data-label="Module">{module.name}</td><td data-label="Status"><StatusBadge status={module.status} /></td><td data-label="Tasks">{module._count.tasks}</td></tr>)}</tbody></table></div> : <EmptyState title="No modules yet" description="Modules are optional and can be added as this project grows." />}<SectionHeader title="Tasks" meta={`${project.tasks.length} loaded`} />{project.tasks.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Task</th><th>Status</th><th>Priority</th></tr></thead><tbody>{project.tasks.map((task) => <tr key={task.id}><td data-label="Task">{task.title}</td><td data-label="Status"><StatusBadge status={task.status} /></td><td data-label="Priority"><StatusBadge status={task.priority} /></td></tr>)}</tbody></table></div> : <EmptyState title="No tasks yet" description="Tasks will appear here when the delivery team starts work." />}</div><aside className="form-panel"><SectionHeader title="Team" meta={`${project.members.length} active`} /><p className="record-meta">Owner · {project.owner?.fullName ?? "Unassigned"}</p><p className="record-meta">Manager · {project.manager?.fullName ?? "Unassigned"}</p><p className="record-meta">Technical owner · {project.technicalOwner?.fullName ?? "Unassigned"}</p><div className="mt-6 space-y-4">{project.members.map((member) => <div key={member.id}><p className="record-title">{member.user.fullName}</p><p className="record-meta">{member.projectRole} · {member.user.role.name}</p></div>)}</div></aside></div></section>;
}
