"use client";
import { useState, type FormEvent } from "react";
import { Button, Field, Input, Select, Notice, SectionHeader } from "@/components/ui/primitives";
import { useResource } from "@/components/ui/resource";

type Client = { id: string; name: string; email?: string | null };
type Family = { id: string; code: string; name: string };
export function FinanceProjectForm() {
  const clients = useResource<Client[]>("/api/clients", "clients"); const families = useResource<Family[]>("/api/project-families", "families");
  const [form, setForm] = useState({ name: "", clientId: "", familyId: "", description: "", projectType: "CLIENT_PROJECT", dealValue: "", expectedDeliveryDate: "", paymentDueDate: "", paymentStructureNotes: "", priority: "MEDIUM" });
  const [state, setState] = useState<{ loading: boolean; message?: string; error?: string }>({ loading: false });
  async function submit(event: FormEvent) { event.preventDefault(); setState({ loading: true }); try { const response = await fetch("/api/finance/projects", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, dealValue: form.dealValue ? Number(form.dealValue) : undefined }) }); const result = await response.json() as { project?: { projectCode: string }; error?: string }; if (!response.ok) throw new Error(result.error ?? "Unable to create project"); setState({ loading: false, message: `${result.project?.projectCode ?? "Project"} created in Planning and CTO notified.` }); setForm({ ...form, name: "", description: "", dealValue: "", paymentStructureNotes: "" }); } catch (error) { setState({ loading: false, error: error instanceof Error ? error.message : "Unable to create project" }); } }
  return <div className="form-panel"><SectionHeader title="Create business project" meta="Finance handoff → CTO" /><form className="form-stack" onSubmit={submit}>{state.error && <Notice>{state.error}</Notice>}{state.message && <Notice success>{state.message}</Notice>}<Field label="Existing client *"><Select required value={form.clientId} onChange={(event) => setForm({ ...form, clientId: event.target.value })}><option value="">{clients.loading ? "Loading clients…" : "Select client"}</option>{clients.data?.map((client) => <option key={client.id} value={client.id}>{client.name}{client.email ? ` · ${client.email}` : ""}</option>)}</Select></Field><Field label="Project family *"><Select required value={form.familyId} onChange={(event) => setForm({ ...form, familyId: event.target.value })}><option value="">{families.loading ? "Loading families…" : "Select family"}</option>{families.data?.map((family) => <option key={family.id} value={family.id}>{family.code} — {family.name}</option>)}</Select></Field><Field label="Project name *"><Input required maxLength={200} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field><Field label="Description"><textarea className="input" rows={4} maxLength={10000} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></Field><Field label="Service type"><Select value={form.projectType} onChange={(event) => setForm({ ...form, projectType: event.target.value })}>{["CLIENT_PROJECT", "INTERNAL_PRODUCT", "INTERNAL_TOOL", "R_AND_D"].map((type) => <option key={type}>{type}</option>)}</Select></Field><div className="form-grid"><Field label="Project value (INR)"><Input type="number" min="0" step="0.01" value={form.dealValue} onChange={(event) => setForm({ ...form, dealValue: event.target.value })} /></Field><Field label="Priority"><Select value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></Select></Field><Field label="Target delivery"><Input type="date" value={form.expectedDeliveryDate} onChange={(event) => setForm({ ...form, expectedDeliveryDate: event.target.value })} /></Field><Field label="Payment due date"><Input type="date" value={form.paymentDueDate} onChange={(event) => setForm({ ...form, paymentDueDate: event.target.value })} /></Field></div><Field label="Payment structure / commercial notes"><textarea className="input" rows={3} maxLength={5000} value={form.paymentStructureNotes} onChange={(event) => setForm({ ...form, paymentStructureNotes: event.target.value })} /></Field><Button type="submit" disabled={state.loading}>{state.loading ? "Creating…" : "Create project ↗"}</Button></form></div>;
}
