"use client";
import { useState, type FormEvent } from "react";
import { CreateForm, ResourcePage, useResource } from "@/components/ui/resource";
import { Button, Field, Input, Select, StatusBadge, Notice, humanize, money, SectionHeader, EmptyState } from "@/components/ui/primitives";
type Transaction = { id: string; transactionNumber: string; type: string; amount: string; currency: string; transactionDate: string; status: string; client?: { name: string } | null };
type Client = { id: string; name: string };
type Quotation = { id: string; proposalNumber: string; title: string; status: string; amount: string | null; currency: string; client?: { name: string; email: string | null } | null; project?: { name: string } | null; sentAt: string | null; acceptedAt: string | null };
const products = ["CRM", "Custom Software", "Custom Automation", "Whatsapp Bot", "Website", "ERP"];
function QuotationCreateForm() {
  const [form, setForm] = useState({ clientId: "", projectId: "", title: "", amount: "", expiresAt: "" });
  const [document, setDocument] = useState<File | null>(null);
  const [state, setState] = useState<{ loading: boolean; message?: string; error?: string }>({ loading: false });
  const clients = useResource<Client[]>("/api/clients", "clients");
  const projects = useResource<{ id: string; name: string; projectCode: string }[]>("/api/projects", "projects");
  async function submit(event: FormEvent) {
    event.preventDefault(); setState({ loading: true });
    const body = new FormData(); Object.entries(form).forEach(([key, value]) => body.set(key, value)); if (document) body.set("document", document);
    try { const response = await fetch("/api/finance/quotations", { method: "POST", body }); const result = await response.json() as { quotation?: { proposalNumber: string }; error?: string }; if (!response.ok) throw new Error(result.error ?? "Unable to create quotation"); setState({ loading: false, message: `${result.quotation?.proposalNumber ?? "Quotation"} created and stored in MinIO.` }); setForm({ ...form, title: "", amount: "", expiresAt: "" }); setDocument(null); }
    catch (error) { setState({ loading: false, error: error instanceof Error ? error.message : "Unable to create quotation" }); }
  }
  return <div className="form-panel mb-8"><SectionHeader title="Create final quotation" meta="PDF required / MinIO" /><form onSubmit={submit} className="form-stack">{state.error && <Notice>{state.error}</Notice>}{state.message && <Notice success>{state.message}</Notice>}<Field label="Client *"><Select required value={form.clientId} onChange={(e) => setForm({ ...form, clientId: e.target.value })}><option value="">{clients.loading ? "Loading clients…" : "Select client"}</option>{clients.data?.map((client) => <option value={client.id} key={client.id}>{client.name}</option>)}</Select></Field><Field label="Project"><Select value={form.projectId} onChange={(e) => setForm({ ...form, projectId: e.target.value })}><option value="">No project linked</option>{projects.data?.map((project) => <option value={project.id} key={project.id}>{project.projectCode} · {project.name}</option>)}</Select></Field><Field label="Title *"><Input required maxLength={200} placeholder="School ERP implementation" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></Field><div className="form-grid"><Field label="Amount (INR) *"><Input required type="number" min="0" step="0.01" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></Field><Field label="Valid until *"><Input required type="date" value={form.expiresAt} onChange={(e) => setForm({ ...form, expiresAt: e.target.value })} /></Field></div><Field label="Final quotation PDF *" hint="PDF only · the binary is stored privately in MinIO; MySQL stores its file ID"><Input required type="file" accept="application/pdf,.pdf" onChange={(e) => setDocument(e.target.files?.[0] ?? null)} /></Field><Button type="submit" disabled={state.loading}>{state.loading ? "Saving…" : "Create final quotation ↗"}</Button></form></div>;
}
export function FinancePage({ initialView = "overview" }: { initialView?: "overview" | "transactions" | "quotations" | "invoice" }) {
  const [view] = useState<"transactions" | "quotations" | "invoice">(initialView === "overview" ? "transactions" : initialView);
  const [form, setForm] = useState({ type: "PAYMENT_RECEIVED", clientId: "", projectId: "", amount: "", transactionDate: new Date().toISOString().slice(0, 10), paymentMethod: "Bank transfer", referenceNumber: "", description: "", document: null as File | null });
  const [invoiceForm, setInvoiceForm] = useState({ companyName: "", clientId: "", invoiceDate: new Date().toISOString().slice(0, 10), product: products[0], amount: "", notes: "" });
  const [invoiceState, setInvoiceState] = useState<{ loading: boolean; message?: string; error?: string }>({ loading: false });
  const clients = useResource<Client[]>("/api/clients", "clients");
  const quotations = useResource<Quotation[]>("/api/finance/quotations", "finance-quotations");
  async function generateInvoice(event: FormEvent) {
    event.preventDefault(); setInvoiceState({ loading: true });
    try {
      const response = await fetch("/api/finance/invoices", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...invoiceForm, amount: Number(invoiceForm.amount) }) });
      const payload = await response.json() as { invoice?: { invoiceNumber: string; id: string }; error?: string };
      if (!response.ok) throw new Error(payload.error ?? "Unable to generate invoice");
      setInvoiceState({ loading: false, message: `Invoice ${payload.invoice?.invoiceNumber ?? payload.invoice?.id} generated and stored in MinIO.` });
      setInvoiceForm({ ...invoiceForm, amount: "", notes: "" });
    } catch (error) { setInvoiceState({ loading: false, error: error instanceof Error ? error.message : "Unable to generate invoice" }); }
  }
  if (initialView === "overview") return <section><div className="page-header"><div><p className="eyebrow">05 / Finance</p><h1>Finance, with a clear next action.</h1><p>Choose Invoice Generation, Final Quotation, or Add Transaction from the Finance section in the sidebar.</p></div></div><div className="route-grid"><div className="route-card"><p className="eyebrow">01</p><h2>Invoice Generation</h2><p>Generate and review client invoices.</p></div><div className="route-card"><p className="eyebrow">02</p><h2>Final Quotation</h2><p>Review commercial quotations and their status.</p></div><div className="route-card"><p className="eyebrow">03</p><h2>Add Transaction</h2><p>Record payments and supporting documents.</p></div></div></section>;
  if (view === "quotations") return <><div className="page-header"><div><p className="eyebrow">05 / Finance / Final Quotation</p><h1>Final quotations, ready to review.</h1><p>Review the quotations that have been sent or accepted before turning them into delivery work.</p></div></div><QuotationCreateForm />{quotations.loading && <p className="muted">Loading quotations…</p>}{quotations.error && <Notice>Final quotations could not be loaded. Check your finance permissions and retry.</Notice>}{quotations.data?.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Quotation</th><th>Client</th><th>Value</th><th>Status</th></tr></thead><tbody>{quotations.data.map((quotation) => <tr key={quotation.id}><td data-label="Quotation"><p className="record-title mono">{quotation.proposalNumber}</p><p className="record-meta">{quotation.title}{quotation.project ? ` · ${quotation.project.name}` : ""}</p></td><td data-label="Client">{quotation.client?.name ?? "Unlinked"}</td><td data-label="Value" className="mono">{money(quotation.amount, quotation.currency)}</td><td data-label="Status"><StatusBadge status={quotation.status} /></td></tr>)}</tbody></table></div> : !quotations.loading && <EmptyState title="No final quotations yet" description="Final, sent, and accepted proposals will appear here." />}</>;
  if (view === "invoice") return <><div className="page-header"><div><p className="eyebrow">05 / Finance / Invoice Generation</p><h1>Generate an invoice.</h1><p>Enter the billing placeholders, select the product, and create a uniquely identified invoice document.</p></div></div><div className="form-card max-w-3xl"><SectionHeader title="Invoice details" meta="PDF pipeline / private MinIO storage" /><form onSubmit={generateInvoice} className="form-grid">{invoiceState.error && <Notice>{invoiceState.error}</Notice>}{invoiceState.message && <Notice success>{invoiceState.message}</Notice>}<Field label="Company name *"><Input required maxLength={200} placeholder="Acme Technologies Pvt. Ltd." value={invoiceForm.companyName} onChange={(e) => setInvoiceForm({ ...invoiceForm, companyName: e.target.value })} /></Field><Field label="Client record *"><Select required value={invoiceForm.clientId} onChange={(e) => setInvoiceForm({ ...invoiceForm, clientId: e.target.value })}><option value="">{clients.loading ? "Loading clients…" : "Select client"}</option>{clients.data?.map((client) => <option value={client.id} key={client.id}>{client.name}</option>)}</Select></Field><Field label="Invoice date *"><Input required type="date" value={invoiceForm.invoiceDate} onChange={(e) => setInvoiceForm({ ...invoiceForm, invoiceDate: e.target.value })} /></Field><Field label="Product *"><Select required value={invoiceForm.product} onChange={(e) => setInvoiceForm({ ...invoiceForm, product: e.target.value })}>{products.map((product) => <option key={product}>{product}</option>)}</Select></Field><Field label="Amount (INR) *"><Input required type="number" min="0.01" step="0.01" value={invoiceForm.amount} onChange={(e) => setInvoiceForm({ ...invoiceForm, amount: e.target.value })} /></Field><Field label="Notes"><textarea className="input" rows={3} maxLength={5000} placeholder="Optional billing notes" value={invoiceForm.notes} onChange={(e) => setInvoiceForm({ ...invoiceForm, notes: e.target.value })} /></Field><Button type="submit" disabled={invoiceState.loading}>{invoiceState.loading ? "Generating…" : "Generate invoice ↗"}</Button></form></div></>;
  return <ResourcePage<Transaction> eyebrow="05 / Finance / Add Transaction" title="Record a transaction." description="Record payments, expenses, and transfers. Keep the financial picture clear." endpoint="/api/finance/transactions" resourceKey="transactions" searchText={(record) => `${record.transactionNumber} ${record.type} ${record.client?.name ?? ""} ${record.status}`}
    columns={[
      { label: "Transaction", render: (record) => <><p className="record-title mono">{record.transactionNumber}</p><p className="record-meta">{humanize(record.type)} · {record.client?.name ?? "Unlinked"}</p></> },
      { label: "Amount", render: (record) => <><p className="mono">{money(record.amount, record.currency)}</p><p className="record-meta">{new Date(record.transactionDate).toLocaleDateString("en-IN")}</p></> },
      { label: "Status", render: (record) => <StatusBadge status={record.status} /> },
    ]}
    form={(reload) => <CreateForm title="Record transaction" endpoint="/api/finance/transactions" payload={() => { const payload = new FormData(); payload.set("type", form.type); payload.set("clientId", form.clientId); payload.set("projectId", form.projectId); payload.set("amount", form.amount); payload.set("transactionDate", form.transactionDate); payload.set("paymentMethod", form.paymentMethod); payload.set("referenceNumber", form.referenceNumber); payload.set("description", form.description); if (form.document) payload.set("document", form.document); return payload; }} reset={() => setForm({ ...form, amount: "", description: "", referenceNumber: "", document: null })} reload={reload} submitLabel="Save transaction ↗">
      <Field label="Type *"><Select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}>{["PAYMENT_RECEIVED", "EXPENSE", "REFUND", "TRANSFER", "OTHER_INCOME", "OTHER"].map((type) => <option value={type} key={type}>{humanize(type)}</option>)}</Select></Field>
      {clients.error && <Notice>Client choices could not be loaded. Refresh the page to retry.</Notice>}
      <Field label={`Client${form.type === "PAYMENT_RECEIVED" ? " *" : ""}`} hint="Required for received payments."><Select required={form.type === "PAYMENT_RECEIVED"} value={form.clientId} onChange={(e) => setForm({ ...form, clientId: e.target.value })}><option value="">{clients.loading ? "Loading clients…" : "Select client"}</option>{clients.data?.map((client) => <option value={client.id} key={client.id}>{client.name}</option>)}</Select></Field>
      <Field label="Amount (INR) *"><Input required type="number" min="0.01" step="0.01" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></Field>
      <Field label="Date *"><Input required type="date" value={form.transactionDate} onChange={(e) => setForm({ ...form, transactionDate: e.target.value })} /></Field>
      <Field label="Payment method"><Input maxLength={60} value={form.paymentMethod} onChange={(e) => setForm({ ...form, paymentMethod: e.target.value })} /></Field>
      <Field label="Reference / UTR"><Input maxLength={120} value={form.referenceNumber} onChange={(e) => setForm({ ...form, referenceNumber: e.target.value })} /></Field>
      <Field label="Description"><textarea className="input" rows={3} maxLength={5000} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field>
      <Field label="Supporting document" hint="Optional · PDF, JPEG, JPG, or PNG · max 10 MB"><Input type="file" accept="application/pdf,image/jpeg,image/png,.pdf,.jpg,.jpeg,.png" onChange={(e) => setForm({ ...form, document: e.target.files?.[0] ?? null })} /></Field>
    </CreateForm>} />;
}
