import { NextResponse } from "next/server";
import { requireAnyPermission, requirePermission } from "@/lib/auth/permissions";
import { prisma } from "@/lib/db/prisma";
import { recordActivity } from "@/lib/activity/service";
import { apiError, unknownApiError } from "@/lib/api/response";
import { projectVisibilityWhere } from "@/lib/projects/access";

export async function GET(_: Request, context: { params: Promise<{ id: string }> }) { try { await requireAnyPermission(["project.view", "project.view_all", "project.view_department", "project.view_assigned"]); const { id } = await context.params; const modules = await prisma.projectModule.findMany({ where: { projectId: id }, include: { owner: { select: { fullName: true } }, _count: { select: { tasks: true } } }, orderBy: { sortOrder: "asc" } }); return NextResponse.json({ modules }); } catch (error) { return error instanceof Error && error.message === "FORBIDDEN" ? apiError("Forbidden", 403) : apiError("Unable to load project modules", 500); } }
export async function POST(request: Request, context: { params: Promise<{ id: string }> }) { try { const actor = await requirePermission("project.manage_modules"); const { id } = await context.params; const body = await request.json() as { name?: string; description?: string; ownerUserId?: string; status?: string; sortOrder?: number }; if (!body.name?.trim()) return apiError("A module name is required"); const visibility = await projectVisibilityWhere(actor.id); const project = await prisma.project.findFirst({ where: { AND: [{ id }, visibility] } }); if (!project) return apiError("You do not have permission to manage this project", 403); const module = await prisma.projectModule.create({ data: { projectId: id, name: body.name.trim(), description: body.description, ownerUserId: body.ownerUserId, status: body.status ?? "PLANNED", sortOrder: body.sortOrder ?? 0 } }); await recordActivity({ activityType: "project.module_created", actorUserId: actor.id, entityType: "project_module", entityId: module.id, parentEntityType: "project", parentEntityId: id, summary: `${actor.fullName} created module “${module.name}”.` }); return NextResponse.json({ module }, { status: 201 }); } catch (error) { return error instanceof Error && error.message === "FORBIDDEN" ? apiError("Forbidden", 403) : unknownApiError(); } }
