import { NextResponse } from "next/server";
import { requirePermission } from "@/lib/auth/permissions";
import { prisma } from "@/lib/db/prisma";
import { recordActivity } from "@/lib/activity/service";
import { recordAudit } from "@/lib/audit/service";
import { apiError, unknownApiError } from "@/lib/api/response";
import { transactionCreateSchema } from "@/lib/validation/crm";

export async function GET() { try { await requirePermission("finance.view"); const transactions = await prisma.transaction.findMany({ include: { client: true, project: true, invoice: true }, orderBy: { transactionDate: "desc" }, take: 200 }); return NextResponse.json({ transactions }); } catch (error) { return error instanceof Error && error.message === "UNAUTHENTICATED" ? apiError("Authentication required", 401) : error instanceof Error && error.message === "FORBIDDEN" ? apiError("Forbidden", 403) : apiError("Unable to load transactions", 500); } }
export async function POST(request: Request) { try { const user = await requirePermission("finance.transaction.create"); const input = transactionCreateSchema.parse(await request.json()); if (input.type === "PAYMENT_RECEIVED" && !input.clientId) return apiError("A client is required for received payments"); const { generateInvoice: _generateInvoice, ...transactionInput } = input; const transaction = await prisma.transaction.create({ data: { ...transactionInput, transactionNumber: `TT-TXN-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`, transactionDate: new Date(`${input.transactionDate}T00:00:00Z`), recordedById: user.id, currency: input.currency.toUpperCase() } }); await recordActivity({ activityType: "transaction.recorded", actorUserId: user.id, entityType: "transaction", entityId: transaction.id, summary: `${user.fullName} recorded ${transaction.type} ${transaction.currency} ${transaction.amount}.` }); await recordAudit({ actorUserId: user.id, action: "transaction.create", entityType: "transaction", entityId: transaction.id, after: { type: transaction.type, amount: transaction.amount.toString() } }); return NextResponse.json({ transaction }, { status: 201 }); } catch (error) { return error && typeof error === "object" && "name" in error && error.name === "ZodError" ? apiError("Invalid transaction data") : unknownApiError(); } }
